version: '4.32.0'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: nexotvDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
